flowchart LR
  D[All data] --> Tr["<b style='color:#137333'>Training set</b> ~70%<br/>model learns here"]
  D --> Va["<b style='color:#1a73a8'>Validation set</b> ~15%<br/>tune choices here"]
  D --> Te["<b style='color:#b8232f'>Test set</b> ~15%<br/>final, honest grade"]
